name: fin_ls
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - streamlit
  - plotly
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.1=py310h70ea87e_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alembic=1.17.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - arrow-cpp=21.0.0=h0399227_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=hef2a5b8_1
  - aws-c-common=0.12.4=hfd05255_0
  - aws-c-compression=0.3.1=ha8a2810_6
  - aws-c-event-stream=0.5.6=hdc32d89_1
  - aws-c-http=0.10.4=hce07812_1
  - aws-c-io=0.21.4=h20b9e97_1
  - aws-c-mqtt=0.13.3=hc9a9668_4
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=ha8a2810_1
  - aws-checksums=0.2.7=ha8a2810_2
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - bcrypt=5.0.0=py310h034784e_0
  - blas=1.0=mkl
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.0.9=hcfcfb64_9
  - brotli-bin=1.0.9=hcfcfb64_9
  - brotlicffi=1.0.9.2=py310h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.10.5=h4c7d964_0
  - cachetools=6.2.1=pyhd8ed1ab_0
  - certifi=2025.10.5=py310haa95532_0
  - cffi=2.0.0=py310h02ab6af_0
  - click=8.3.0=pyh7428d3b_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310hc19bc0b_0
  - cryptography=46.0.3=py310he482ccc_0
  - cuda-cccl=13.0.85=h5221881_1
  - cuda-cccl_win-64=13.0.85=hc667259_1
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-libraries-dev=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvrtc-dev=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=13.0.85=h17533db_0
  - cuda-opencl-dev=13.0.85=hde976d8_0
  - cuda-profiler-api=13.0.85=h5221881_0
  - cuda-runtime=12.4.1=0
  - cuda-version=13.0=3
  - cycler=0.12.1=pyhd8ed1ab_1
  - databricks-sdk=0.70.0=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - dnspython=2.7.0=pyhff2d567_1
  - docker-py=7.1.0=pyhd8ed1ab_1
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - fastapi=0.119.1=h30ea78e_0
  - fastapi-cli=0.0.13=pyhcf101f3_0
  - fastapi-core=0.119.1=pyhcf101f3_0
  - filelock=3.17.0=py310haa95532_0
  - flask=3.1.2=pyhd8ed1ab_0
  - flask-cors=6.0.1=pyhe01879c_0
  - fonttools=4.60.1=py310hdb0e946_0
  - freetype=2.13.3=h0620614_0
  - frozenlist=1.7.0=py310had1666a_0
  - gflags=2.2.2=he0c23c2_1005
  - giflib=5.2.2=h7edc060_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glog=0.5.0=h4797de2_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py310h827c3e9_0
  - google-auth=2.41.1=pyhd8ed1ab_0
  - graphene=3.4.3=pyhd8ed1ab_1
  - graphql-core=3.2.6=pyh29332c3_0
  - graphql-relay=3.2.0=pyhd8ed1ab_1
  - greenlet=3.2.4=py310h73ae2b4_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py310h29418f3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2023.1.0=h59b6b97_46320
  - invoke=2.2.1=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=py310haa95532_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jpeg=9f=ha349fce_0
  - khronos-opencl-icd-loader=2024.05.08=h8cc25b3_0
  - kiwisolver=1.4.9=py310h1e1005b_1
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20250127.0=cxx17_h4eb7d71_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.0.9=hcfcfb64_9
  - libbrotlidec=1.0.9=hcfcfb64_9
  - libbrotlienc=1.0.9=hcfcfb64_9
  - libcblas=3.9.0=12_hb3dda5d_netlib
  - libcublas=12.4.5.8=0
  - libcublas-dev=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufft-dev=11.2.1.3=0
  - libcurand=10.4.0.35=h86a452a_1
  - libcurand-dev=10.4.0.35=hde976d8_1
  - libcurl=8.16.0=h43ecb02_0
  - libcusolver=11.6.1.9=0
  - libcusolver-dev=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libcusparse-dev=12.3.1.170=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgrpc=1.71.0=h35301be_0
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - liblapack=3.9.0=12_h13b7882_netlib
  - libnpp=12.2.5.30=0
  - libnpp-dev=12.2.5.30=0
  - libnvfatbin=13.0.85=h17533db_0
  - libnvfatbin-dev=13.0.85=h17533db_0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libnvjpeg-dev=12.3.1.117=0
  - libpng=1.6.50=h46444df_0
  - libprotobuf=5.29.3=he9d8c4a_0
  - libre2-11=2024.07.02=hd248061_3
  - libsodium=1.0.20=hc70643c_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.15.0=h532d1ae_1
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mako=1.3.10=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - matplotlib-base=3.10.6=py310h0bdd906_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - mlflow=3.5.1=h5588dad_1
  - mlflow-skinny=3.5.1=h5588dad_1
  - mlflow-ui=3.5.1=py310h5588dad_1
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py310haa95532_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.6.3=py310hdb0e946_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - networkx=3.4.2=py310haa95532_0
  - numpy-base=2.0.1=py310h65a83cf_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.5.4=h725018a_0
  - opentelemetry-api=1.38.0=pyhd8ed1ab_0
  - opentelemetry-proto=1.38.0=pyhd8ed1ab_0
  - opentelemetry-sdk=1.38.0=pyhd8ed1ab_0
  - opentelemetry-semantic-conventions=0.59b0=pyh3cfb1c2_0
  - orc=2.2.0=hf43e1a1_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310hed136d8_1
  - paramiko=4.0.0=pyhd8ed1ab_0
  - pillow=11.1.0=py310h096bfcc_0
  - pip=25.2=pyhc872135_1
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.2=pyhd8ed1ab_0
  - propcache=0.3.1=py310h38315fa_0
  - pyarrow=21.0.0=py310ha5e6156_0
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.23=py310haa95532_0
  - pydantic=2.12.3=pyh3cfb1c2_0
  - pydantic-core=2.41.4=py310h034784e_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynacl=1.6.0=py310h29418f3_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.1.1=pyhe01879c_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=2.5.1=py3.10_cuda12.4_cudnn9_0
  - pytorch-cuda=12.4=h3fd98bf_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pywin32=311=py310h282bd7d_1
  - pywin32-on-windows=0.1.0=pyh07e9846_2
  - pyyaml=6.0.2=py310h827c3e9_0
  - qhull=2020.2=hc790b64_5
  - querystring_parser=1.2.4=pyhd8ed1ab_2
  - re2=2024.07.02=haf4117d_3
  - requests=2.32.5=py310haa95532_0
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.15.1=pyhcf101f3_0
  - rsa=4.9.1=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py310h21054b0_0
  - scipy=1.15.2=py310h15c175c_0
  - setuptools=80.9.0=py310haa95532_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h7fa0ca8_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlalchemy=2.0.44=py310h29418f3_0
  - sqlite=3.50.2=hda9a48d_1
  - sqlparse=0.5.3=pyhd8ed1ab_0
  - starlette=0.48.0=pyhfdc7a7d_0
  - sympy=1.14.0=py310haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - tomli=2.3.0=pyhcf101f3_0
  - typer=0.20.0=pyhdb1f59b_0
  - typer-slim=0.20.0=pyhcf101f3_0
  - typer-slim-standard=0.20.0=h65a100f_0
  - typing-extensions=4.15.0=py310haa95532_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=py310haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=16.0.0=py310h29418f3_1
  - urllib3=2.5.0=py310haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - uvicorn=0.38.0=pyh5737063_0
  - uvicorn-standard=0.38.0=h5737063_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - waitress=3.0.2=pyhd8ed1ab_1
  - watchfiles=1.1.1=py310hf13f778_0
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - websockets=15.0.1=py310h1637853_2
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yarl=1.22.0=py310hdb0e946_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - streamlit-option-menu
      - streamlit-plotly-events
      - absl-py==2.3.1
      - astunparse==1.6.3
      - charset-normalizer==3.4.4
      - colorlog==6.10.1
      - flatbuffers==25.9.23
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - keras==3.11.3
      - libclang==18.1.1
      - markdown==3.9
      - markupsafe==3.0.3
      - ml-dtypes==0.4.1
      - namex==0.1.0
      - numpy==1.26.4
      - opt-einsum==3.4.0
      - optree==0.17.0
      - optuna==4.5.0
      - protobuf==4.25.3
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - tensorflow-intel==2.17.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.2.0
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - wrapt==2.0.0


